var searchData=
[
  ['os_5fcore_2ec_283',['os_core.c',['../os__core_8c.html',1,'']]],
  ['os_5fcore_2eh_284',['os_core.h',['../os__core_8h.html',1,'']]],
  ['os_5finput_2ec_285',['os_input.c',['../os__input_8c.html',1,'']]],
  ['os_5finput_2eh_286',['os_input.h',['../os__input_8h.html',1,'']]],
  ['os_5fmem_5fdrivers_2ec_287',['os_mem_drivers.c',['../os__mem__drivers_8c.html',1,'']]],
  ['os_5fmem_5fdrivers_2eh_288',['os_mem_drivers.h',['../os__mem__drivers_8h.html',1,'']]],
  ['os_5fmemheap_5fdrivers_2ec_289',['os_memheap_drivers.c',['../os__memheap__drivers_8c.html',1,'']]],
  ['os_5fmemheap_5fdrivers_2eh_290',['os_memheap_drivers.h',['../os__memheap__drivers_8h.html',1,'']]],
  ['os_5fmemory_2ec_291',['os_memory.c',['../os__memory_8c.html',1,'']]],
  ['os_5fmemory_2eh_292',['os_memory.h',['../os__memory_8h.html',1,'']]],
  ['os_5fmemory_5fstrategies_2ec_293',['os_memory_strategies.c',['../os__memory__strategies_8c.html',1,'']]],
  ['os_5fmemory_5fstrategies_2eh_294',['os_memory_strategies.h',['../os__memory__strategies_8h.html',1,'']]],
  ['os_5fprocess_2eh_295',['os_process.h',['../os__process_8h.html',1,'']]],
  ['os_5fscheduler_2ec_296',['os_scheduler.c',['../os__scheduler_8c.html',1,'']]],
  ['os_5fscheduler_2eh_297',['os_scheduler.h',['../os__scheduler_8h.html',1,'']]],
  ['os_5fscheduling_5fstrategies_2ec_298',['os_scheduling_strategies.c',['../os__scheduling__strategies_8c.html',1,'']]],
  ['os_5fscheduling_5fstrategies_2eh_299',['os_scheduling_strategies.h',['../os__scheduling__strategies_8h.html',1,'']]],
  ['os_5ftaskman_2ec_300',['os_taskman.c',['../os__taskman_8c.html',1,'']]],
  ['os_5ftaskman_2eh_301',['os_taskman.h',['../os__taskman_8h.html',1,'']]],
  ['os_5fuser_5fprivileges_2eh_302',['os_user_privileges.h',['../os__user__privileges_8h.html',1,'']]]
];
